version: '3.8'

services:
  backend-app:
    build: .
    expose:
      - "8080"
    restart: always

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depend_on:
      - backend-app
    restart: always          