name: Build, Push to GHCR, and Deploy to EC2

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'  
env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest 
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Build and Tag Docker Image
        run: |
          LOWER_IMAGE_NAME=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          docker build \
            -t ${{ env.REGISTRY }}/$LOWER_IMAGE_NAME:latest \
            -t ${{ env.REGISTRY }}/$LOWER_IMAGE_NAME:${{ github.sha }} \
            -f ./Dockerfile .

      - name: Push Docker Image
        run: |
          LOWER_IMAGE_NAME=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          docker push ${{ env.REGISTRY }}/$LOWER_IMAGE_NAME:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push 

    steps:
      - name: Deploy on EC2
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh 
          chmod 700 ~/.ssh 
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/~/.ssh/known_hosts
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

          LOWER_IMAGE_NAME=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')

          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin 

          docker stop spring-nginx-app || true
          docker rm spring-nginx-app || true

          docker pull ${{ env.REGISTRY }}/$LOWER_IMAGE_NAME:latest 

          docker run -d \
            --name spring-nginx-app \
            --restart always \
            --network hosts \
            ${{ env.REGISTRY }}/$LOWER_IMAGE_NAME:latest 

            docker image prune -f 

            docker ps --filter "name=spring-nginx-app"

            docker logs spring-nginx-app
          EOF   

